export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_FOCUS_NODE = 'UPDATE_FOCUS_NODE';
export const UPDATE_GRAPH = 'UPDATE_GRAPH';
export const SHOW_PROGRESS_SPINNER = 'SHOW_PROGRESS_SPINNER';
export const HIDE_PROGRESS_SPINNER = 'HIDE_PROGRESS_SPINNER';