export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_FOCUS_NODE = 'UPDATE_FOCUS_NODE';
export const UPDATE_GRAPH = 'UPDATE_GRAPH';
export const SHOW_PROGRESS_SPINNER = 'SHOW_PROGRESS_SPINNER';
export const HIDE_PROGRESS_SPINNER = 'HIDE_PROGRESS_SPINNER';
export const SHOW_DRAWER_SEARCH_RESULTS = 'SHOW_DRAWER_SEARCH_RESULTS';
export const HIDE_DRAWER_SEARCH_RESULTS = 'HIDE_DRAWER_SEARCH_RESULTS';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
